services:
  - type: web
    name: ai-interview-assistant
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn 11labs_v3:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: ELEVENLABS_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false 